# Generated by Django 4.2.1 on 2023-05-25 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0009_merge_20230430_2109'),
        ('Plato', '0006_remove_oferta_es_oferta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.consumidor')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plato.oferta')),
            ],
        ),
    ]
