# Generated by Django 4.1.2 on 2023-04-30 00:11

import django.contrib.auth.models
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_consumidor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Usuarios.user',),
            managers=[
                ('restaurante', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
