# Generated by Django 4.1.2 on 2023-04-30 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_delete_consumidor_delete_restaurante_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='es_Consumidor',
            new_name='is_Consumidor',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='es_Restaurante',
            new_name='is_Restaurante',
        ),
    ]
