# Generated by Django 4.1.6 on 2023-04-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0007_rename_is_cestaurante_user_is_restaurante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='Nombre_Marca',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
