# Generated by Django 4.1.6 on 2023-05-01 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0008_alter_restaurante_nombre_marca'),
        ('Usuarios', '0008_remove_restaurante_id_restaurante_user'),
    ]

    operations = [
    ]
