# Generated by Django 4.1.2 on 2023-05-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0009_merge_20230430_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumidor',
            name='bio',
            field=models.TextField(default='---------'),
        ),
        migrations.AddField(
            model_name='consumidor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='bio',
            field=models.TextField(default='---------'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen'),
        ),
    ]
