# Generated by Django 4.2.1 on 2023-05-10 17:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0009_merge_20230430_2109'),
        ('Plato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('puntaje_calificacion', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('contenido_comentario', models.CharField(blank=True, max_length=255)),
                ('consumidor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Usuarios.consumidor')),
            ],
        ),
        migrations.CreateModel(
            name='ReseñaApp',
            fields=[
                ('reseña_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Calificaciones.reseña')),
            ],
            bases=('Calificaciones.reseña',),
        ),
        migrations.CreateModel(
            name='ReseñaRestaurante',
            fields=[
                ('reseña_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Calificaciones.reseña')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.restaurante')),
            ],
            bases=('Calificaciones.reseña',),
        ),
        migrations.CreateModel(
            name='ReseñaPlato',
            fields=[
                ('reseña_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Calificaciones.reseña')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plato.plato')),
            ],
            bases=('Calificaciones.reseña',),
        ),
    ]
