# Generated by Django 4.2.1 on 2023-05-12 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseña',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
