# Generated by Django 4.2.1 on 2023-05-12 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Plato', '0002_oferta'),
        ('Calificaciones', '0002_alter_reseña_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReseñaOferta',
            fields=[
                ('reseña_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Calificaciones.reseña')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plato.oferta')),
            ],
            bases=('Calificaciones.reseña',),
        ),
    ]
