# Generated by Django 4.1.6 on 2023-04-30 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0008_alter_restaurante_nombre_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='plato',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('category', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=250)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.restaurante', to_field='Nombre_Marca')),
            ],
        ),
    ]
