# Generated by Django 4.1.6 on 2023-05-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plato', '0003_plato_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='precioNuevo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plato',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
