# Generated by Django 4.1.6 on 2023-05-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plato', '0004_oferta_precionuevo_plato_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='es_oferta',
            field=models.BooleanField(default=True),
        ),
    ]
